import type { Metadata } from "next";
import dayjs from "dayjs";
import "dayjs/locale/id";

import "./globals.css";

dayjs.locale("id");

export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-night">{children}</body>
    </html>
  );
}
